name: $(Build.DefinitionName)_$(Date:yyMMdd).$(Rev:rr)

trigger:
  branches:
    include:
      - main
      - master
  paths:
    exclude:
      - docs/*
pr:
  branches:
    include:
      - '*'
  paths:
    include:
      - '*'
    exclude:
      - README.md
      - docs/*
variables:
  - group: powershell-vargroup

resources:
  repositories:
    - repository: plumber
      type: github
      name: mieel/plumber
      endpoint: mieel
      ref: refs/tags/$(Plumber.StableVersion)

stages:
  - template: azure-pipelines-templates/azure-pipelines-build-publish-psmodule.stage.yml@plumber
    parameters:
      ModuleName: PSAzureAppConfiguration
      ProjectRoot: $(Build.SourcesDirectory)
      GitHubConnection: $(GithubServiceConnection)
      PackageSourceUrl: $(PackageSourceUrl)   # from linked group
      PackageSourcePat: $(PackageSourcePat) # from linked group
      UseGitVersionConfigFile: ./GitVersion.yml  # we need to do this because 'main' is not supported out of the box
      PublishRepoName: PSGallery
